Content the this keyword
nx-academy/nx-academy.github.io pull request #6
Opened 2024-08-12 08:30 UTC by Escanor1986

Création d'une fiche technique sur le keyword "this" en JS.

2024-08-16 06:26 UTC, tdimnet requested changes
Merci Lionel pour ta fiche technique :).

Il y a pas mal de bonnes choses dedans. Il est à la fois très complet et contient beaucoup d'exemples. J'aime bien aussi la manière que tu as de poser des questions à ton audience.

Certaines de tes tournures de phrase sont parfois un peu lourdes. J'ai noté quelques exemples dans la revue de la PR. On pourra prendre le temps d'en discuter ensemble :).

Autre chose, est-ce que tu pourrais ajouter une section ressources à la fin de la fiche ? Ca te permet de donner quelques références pour ce qui veulent aller plus loin.

Je te laisse prendre le temps de lire mes retours et de me dire si tu as des questions et/ou besoin d'aide.

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +description: sd
Tu pourras ajouter une description de ta fiche ? Je me sens pour les meta description :)

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +![Deux personnes dans une cuisine différente, pixel art](/this_context.webp)
Est-ce que tu pourrais changer le nom de ton image pour quelque chose de plus descriptif ? Par exemple, cuisine-separee ?

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Dans le cadre [d'un cours en ligne avancé sur le JavaScript disponible sur la plateforme Udemy](https://www.udemy.com/course/pro-javascript/), qui comprend des cours vidéos ainsi que des supports écr
Ta phrase a une structure un peu lourde. Tu pourrais la fluidifier de cette manière : 

 > Dans le cadre [d'un cours en ligne avancé sur le JavaScript disponible sur la plateforme Udemy](https://www.udemy.com/course/pro-javascript/), qui comprend des cours vidéos ainsi que des supports écrits et des exercices pratiques à réaliser par soi-même, j'ai été confronté à l'utilisation du mot clef "this" lors de la réalisation d'un exo consistant à "revisiter" le jeu Puissance 4 par le biais de la POO (programmation orientée objet).

> J'ai récemment été confronté à l'utilisation du mot clé `this` [dans un cours sur le JavaScript sur Udemy]((https://www.udemy.com/course/pro-javascript/). Le cours proposait de réaliser un jeu de Puissance 4 en programmation orienté objet.

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Dans le cadre [d'un cours en ligne avancé sur le JavaScript disponible sur la plateforme Udemy](https://www.udemy.com/course/pro-javascript/), qui comprend des cours vidéos ainsi que des supports écr
D'une manière générale, quand tu écris, il faut que tu essayes de relire tes phrases à voix haute. Ca te permet de voir si elles font naturelles ou non :).

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Durant ce projet, je me suis particulièrement intéressé à l'utilisation des `classes` et de la manière dont est géré le mot clef "this" dans ce cadre, et en dehors. **Il est primordiale de bien saisi
Pour info, tu n'as pas besoin de mettre `classes` avec des backtics : on s'en sert plutôt quand on est face à du code, par exemple, `.call()` ou `.bind()`.

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Durant ce projet, je me suis particulièrement intéressé à l'utilisation des `classes` et de la manière dont est géré le mot clef "this" dans ce cadre, et en dehors. **Il est primordiale de bien saisi
Autre chose : tu peux fluidifier ta phrase :).

> Durant ce projet, je me suis particulièrement intéressé à l'utilisation des classes et à la manière dont le mot clef "this" est géré.

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Il est souvent méconnu par certains dévéloppeurs dans le cadre d'une utilisation avancé et peut très vite poser de gros problèmes dans l'exécution de votre code s'il n'est pas compris et implémenter
Tu pourrais donner un exemple perso où tu t'es arraché les cheveux ?

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +## Comment utiliser this suivants les cas de figures ?
Ici, tu pourrais changer ton titre par "Les différents cas d'utilisation du this".

Ca te permettrait de virer cette phrase : Passons en revue les différents cas de figure cité ci-dessus :

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +### Utilisation de this dans le contexte Global (objet window dans le navigateur) :
Très bien ! C'est clair et précis comme titre !

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Comme vous le savez certainement, le simple fait de créer un fichier JS (même "vide") et de le charger dans le navigateur aura un effet : **Créer le contexte global, en d'autres termes, l'objet "wind
Tu peux supprimer le début : Comme vous le savez certainement. Ca peut être pris comme de la condescendance

Tu pourrais le remplacer par un "Il faut savoir que" ou "Quand vous créez un fichier JavaScript, même vide,..."

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +```
Top ça !

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Le principe de l'appel de méthode...
Alors question, qu'est-ce que t'apporte cette phrase ? :)

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +> Un petit trick pour se faciliter la vie avec le "this" est de se demander `ce qu'il y a à gauche du .`lorsque vous invoquez une méthode d'un objet. Car lorsque vous appelez cette méthode, **"this"
Très bien ça : aussi bien sur le fond que la forme.
Ca fait comme-ci tu donnais ton petit conseil mircale :)

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> + > Pourquoi ce comportement ?
Idem : je trouve ça très bien cool que tu utilises les citations pour poser tes questions !

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +- Si vous devez `faire appel une seule fois` à une méthode d'instance tout en reliant son "this" à l'objet souhaité, vous pouvez utiliser la méthode `.call()` qui invoquera immédiatemment la fonction
Plutôt que de faire une liste avec -, je te conseille plus de jouer avec les titres :

## Les méthodes d'instances .call(), .apply() && .bind() :

### Le cas de la méthode .call (essaye de trouver un meilleur titre si possible ^^)

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +- Dans un cas similaire, mais où vous souhaitez passer un tableau d'objets en argument, c'est ici alors qu'intervient l'usage de la méthode `.apply()`. La principale différence avec la méthode `.call
Idem ici : tu peux mettre un titre plutôt qu'une puce de liste

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +> Retenons donc jusqu'ici que le comportement du this varie en fonction du contexte dans lequel il est invoqué et en fonction du mode strict ou mode non strict. Suivant ce cas de figures, il peut y a
Très bien de résumer ce que tu viens de voir

2024-08-16 06:26 UTC, tdimnet commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +#### This et les fonctions (fléchées ou non) :
Tu peux changer le titre ici et mettre plutôt : 

## This et les fonctions fléchées

2024-08-22 16:44 UTC, Escanor1986 commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Il est souvent méconnu par certains dévéloppeurs dans le cadre d'une utilisation avancé et peut très vite poser de gros problèmes dans l'exécution de votre code s'il n'est pas compris et implémenter
que penses-tu de "Pour ma part, j'ai rencontré de grosses difficultés lors d'un de mes premiers projets en JavaScript. Je tentais d'utiliser "this" dans un écouteur d'évènement en utilisant une fonction fléchée. Je n'avais pas saisi la subtilité à l'époque ! Nous aborderons d'ailleurs ce point plus loin dans la fiche... !"

2024-08-22 16:48 UTC, Escanor1986 commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Comme vous le savez certainement, le simple fait de créer un fichier JS (même "vide") et de le charger dans le navigateur aura un effet : **Créer le contexte global, en d'autres termes, l'objet "wind
que penses-tu de "Quand vous créez un fichier JavaScript, même vide, et que vous le charger dans le navigateur, cela aura un effet : **Créer le contexte global, en d'autres termes, l'objet "window", objet auquel le fameux "this" fait référence.** Que l'on soit `mode strict`ou `mode non strict`, this fait référence à window. Prenons comme exemple le code suivant, donné comme seule instruction dans votre module JS :" ? :-)

2024-08-22 16:50 UTC, Escanor1986 commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +Le principe de l'appel de méthode...
Rien du tout :-) je me rends compte en relisant ce passage que je comptais démarrer l'explication autrement et je n'ai pas effacer cette phrase surnuméraire !

2024-08-22 16:59 UTC, Escanor1986 commented on src/pages/fiches/comprendre-le-mot-clef-this.md
> +- Si vous devez `faire appel une seule fois` à une méthode d'instance tout en reliant son "this" à l'objet souhaité, vous pouvez utiliser la méthode `.call()` qui invoquera immédiatemment la fonction
"#### Invoquer this à la demande avec .call() :
#### Passez this et ses arguments avec .apply():
#### Fixer this pour de bon avec .bind():
"

2024-10-13 12:22 UTC, merged